### ISSUE TITLE
post-v1.0.0 roadmap

### ISSUE THREAD

**Issue by ThatNerdSquared** [lentoapp/lento#63]
# next steps
- [ ] #38 
- [x] #61 
- [ ] #46
- [ ] #43  
- [ ] #53 
- [ ] #45
- [ ] #57 
- [ ] #52 
- [x] #20 
- [x] #44 
- [ ] #64 

# possible ideas
- [ ] permaban list
- [ ] add stuff to card during block
- [ ] no blocks longer than 24h
- [ ] email to unlock
- [ ] add tests
- [ ] investigate changing theming system to pure python
