### ISSUE TITLE
v1.0.0 roadmap

### ISSUE THREAD

**Issue by ThatNerdSquared** [lentoapp/lento#67]
# v1.0.0

- [ ] repo transfer?
- [ ] #60
- [x] #69
- [ ] add backends for multiple datastores
- [ ] #39
- [ ] add proper cross-platform daemon load system
- [ ] #55 
- [x] #51 
- [ ] refactor card to MVC with sideways listview
- [ ] make add website/app card popup work with QStackedWidget
- [ ] #54 
- [x] #68 
- [x] #56 
- [x] #47 
- [ ] extract toolbar
- [ ] fix proxy controller classes to properly use abstract class
- [ ] #59 
- [ ] #49 
- [ ] #58 
- [ ] Lento website (subset of failsafe)
